### ISSUE TITLE
マンガ・小説の処分

### ISSUE THREAD

**Issue by astapi** [astapi/hikkoshi#4]
実家に送るか・・・。

**Comment by koogawa** [comment]
自分はブックオフで売る派です！
何十冊売って、
数十円にしかならない時もありますが😭

**Comment by rei-m** [comment]
美品だったらメルカリの方がいいかも🤔

**Comment by astapi** [comment]
ブックオフは過去3回大量に売っていて、
今残っているのは売りたくないやつなんですよね😥
かといって、次の物件に持って行きたいかというと持って行かなくてもいい感じ・・・。

**Comment by astapi** [comment]
フィギュア類は昨日いくつかメルカリ出しました！
買った時より軒並み高くなっててちょっとうれしい。

**Comment by koogawa** [comment]
メルカリという手があった！ 😇

**Comment by astapi** [comment]
実家に送った。
