### ISSUE TITLE
引っ越し業者の選択

### ISSUE THREAD

**Issue by astapi** [astapi/hikkoshi#8]
一括見積もりは、電話が来すぎてやばいという話しなので、
なるべく避けて行きたいところ・・・。

**Comment by koogawa** [comment]
今まで選んでよかったところ：
- 0123 のところ
- 某引越し王

大手は高いですが、その分安心感がありました。
「前回もおたくでお願いしました」と言ったら割引してくれました。

**Comment by astapi** [comment]
ありがとうございます！
見積もり依頼してみます😊

**Comment by astapi** [comment]
ヴォイス引っ越しにした。
http://www.voicem.jp/

suumo一括見積もりで一番安かった。
ただ、問い合わせ対応が微妙且つ、見積もり金額に全く根拠がなく、
問い合わせしても教えてもらえなかった。
しかし、それでも安いのでまぁ良しとした。

**Comment by astapi** [comment]
引っ越しは6/22午前
